# Generated by Django 6.0.3 on 2026-03-29 20:55

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HealthMetric',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('metric_type', models.CharField(choices=[('appointments_total', 'Total Appointments'), ('appointments_completed', 'Completed Appointments'), ('lab_tests_total', 'Total Lab Tests'), ('critical_results', 'Critical Lab Results'), ('prescriptions_issued', 'Prescriptions Issued'), ('new_patients', 'New Patients Registered'), ('emergency_requests', 'Emergency Requests')], max_length=50)),
                ('district', models.CharField(blank=True, max_length=100)),
                ('value', models.PositiveIntegerField(default=0)),
                ('date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'health_metrics',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='DiseaseReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('condition_name', models.CharField(max_length=200)),
                ('icd_code', models.CharField(blank=True, max_length=20)),
                ('district', models.CharField(max_length=100)),
                ('period', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly')], default='weekly', max_length=20)),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('case_count', models.PositiveIntegerField(default=0)),
                ('death_count', models.PositiveIntegerField(default=0)),
                ('recovered_count', models.PositiveIntegerField(default=0)),
                ('is_outbreak', models.BooleanField(default=False)),
                ('outbreak_threshold', models.PositiveIntegerField(default=10, help_text='Case count that triggers outbreak flag')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reported_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='disease_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'disease_reports',
                'ordering': ['-period_start'],
                'unique_together': {('condition_name', 'district', 'period_start', 'period')},
            },
        ),
    ]
