# Generated by Django 6.0.3 on 2026-03-29 19:45

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('appointments', '0001_initial'),
        ('patients', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClinicalNote',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('subjective', models.TextField(help_text="Patient's complaints and symptoms in their own words")),
                ('objective', models.TextField(help_text="Doctor's observations, vitals, exam findings")),
                ('assessment', models.TextField(help_text="Doctor's clinical assessment and interpretation")),
                ('plan', models.TextField(help_text='Treatment plan, follow-ups, referrals')),
                ('temperature', models.DecimalField(blank=True, decimal_places=1, help_text='Celsius', max_digits=4, null=True)),
                ('blood_pressure_systolic', models.PositiveIntegerField(blank=True, null=True)),
                ('blood_pressure_diastolic', models.PositiveIntegerField(blank=True, null=True)),
                ('pulse_rate', models.PositiveIntegerField(blank=True, null=True)),
                ('respiratory_rate', models.PositiveIntegerField(blank=True, null=True)),
                ('oxygen_saturation', models.DecimalField(blank=True, decimal_places=1, help_text='SpO2 percentage', max_digits=4, null=True)),
                ('weight_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('height_cm', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('is_finalized', models.BooleanField(default=False, help_text='Finalized notes cannot be edited')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('appointment', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clinical_note', to='appointments.appointment')),
                ('doctor', models.ForeignKey(limit_choices_to={'role': 'doctor'}, on_delete=django.db.models.deletion.CASCADE, related_name='clinical_notes', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clinical_notes', to='patients.patientprofile')),
            ],
            options={
                'db_table': 'clinical_notes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Diagnosis',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('icd_code', models.CharField(blank=True, help_text='ICD-10 code e.g. E11 for Type 2 Diabetes', max_length=20)),
                ('condition_name', models.CharField(max_length=200)),
                ('diagnosis_type', models.CharField(choices=[('primary', 'Primary'), ('secondary', 'Secondary'), ('chronic', 'Chronic')], default='primary', max_length=20)),
                ('severity', models.CharField(choices=[('mild', 'Mild'), ('moderate', 'Moderate'), ('severe', 'Severe'), ('critical', 'Critical')], default='mild', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('diagnosed_date', models.DateField(auto_now_add=True)),
                ('is_resolved', models.BooleanField(default=False)),
                ('resolved_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('clinical_note', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diagnoses', to='records.clinicalnote')),
                ('diagnosed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='diagnoses_made', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diagnoses', to='patients.patientprofile')),
            ],
            options={
                'db_table': 'diagnoses',
                'ordering': ['-diagnosed_date'],
            },
        ),
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('medication_name', models.CharField(max_length=200)),
                ('dosage', models.CharField(help_text='e.g. 500mg', max_length=100)),
                ('frequency', models.CharField(choices=[('once_daily', 'Once daily'), ('twice_daily', 'Twice daily'), ('three_daily', 'Three times daily'), ('four_daily', 'Four times daily'), ('every_8_hours', 'Every 8 hours'), ('as_needed', 'As needed'), ('weekly', 'Weekly')], default='twice_daily', max_length=20)),
                ('duration_days', models.PositiveIntegerField(help_text='Number of days')),
                ('quantity', models.PositiveIntegerField(help_text='Total units to dispense')),
                ('instructions', models.TextField(blank=True, help_text='Special instructions e.g. take with food')),
                ('status', models.CharField(choices=[('active', 'Active'), ('dispensed', 'Dispensed'), ('expired', 'Expired'), ('cancelled', 'Cancelled')], default='active', max_length=20)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('dispensed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('clinical_note', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prescriptions', to='records.clinicalnote')),
                ('dispensed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prescriptions_dispensed', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prescriptions', to='patients.patientprofile')),
                ('prescribed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prescriptions_written', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'prescriptions',
                'ordering': ['-created_at'],
            },
        ),
    ]
